add selector sync
igorlogius/bookmark-router pull request #4
Opened 2023-08-29 09:01 UTC by hermesthecat

2023-08-29 10:16 UTC, igorlogius requested changes

2023-08-29 10:16 UTC, igorlogius commented on options.js
> +  await browser.storage.sync.get("selectors", function (result) {
no callback please

2023-08-29 10:16 UTC, igorlogius commented on options.js
> +     await browser.storage.sync.get("selectors", function (syncResult) {
no callback please

2023-08-29 10:16 UTC, igorlogius commented on options.js
> +  //let res = await browser.storage.local.get('selectors');
no code in comments necessary, can be removed

2023-08-29 10:35 UTC, hermesthecat commented on options.js
> +  let mainTableBody = document.getElementById("mainTableBody");
not important for me, can stay as before.

2023-08-29 11:16 UTC, igorlogius commented
> approve or reject, but I don't have time to deal with it any more.

well, with your consent i'm gonna finish the PR and restructure the necessary elements. 

Thanks for submiting the idea and this inital draft. :+1:

2023-08-29 11:54 UTC, closed without merging

2023-08-30 14:18 UTC, igorlogius commented
Had to make a few more adjustments but ... now a user can make a backup that can be pulled down from any device. An auto-sync options seemed to be a bit more then necessary especially since it always comes with the risk of merge issues/expectations, which i really dont want to deal with. Better to leave that up to the user. 

Sorry if the changes now do not align with your expectations, but i guess you can now just as well maintain your forked version.  

Anyway, thanks for the PRs and conversation and feel free to submit other ideas if you like. 

Have a nice day.